[pytest]
markers =
    smoke: базовые сценарии, которые должны проходить всегда
    regression: полная регрессия
    api: тесты через HTTP API
    auth: тесты, связанные с авторизацией
    critical: критичные тесты
log_cli = true
log_cli_level = INFO
log_format = %(message)s